### ISSUE TITLE
Two types of NaN in Lua

### ISSUE THREAD

**Issue by ghost** [gvx/Ser#4]
LuaJIT 2.0 doesn't seem to disginguish inteterminate from NaN, but Lua 5.1 does. In Lua 5.1, the tostring() of indeterminate forms in my system is `-nan`, in others it may be different. They are distinguished by having the sign bit set.

This causes _ser_ to not always serialize NaNs under Lua correctly (though it correctly outputs indeterminates, and it correctly works under LuaJIT 2.0 in the systems I could test).

This is the suggested replacement:

``` lua
local oddvals = {[tostring(1/0)] = '1/0', [tostring(-1/0)] = '-1/0', [tostring(-(0/0))] = '-(0/0)', [tostring(0/0)] = '0/0'}
```

Under LuaJIT, one overwrites the other.

I tested only with:
- Lua 5.1.5 32 bits on Debian
- LuaJIT 2.0.3 32 bits on Debian
- Lua 5.1.5 32 bits on Windows
- LuaJIT embedded with LÖVE 0.9.1 32 bits on Windows.

Example (Debian 32 bits):

```
$ luajit
LuaJIT 2.0.3 -- Copyright (C) 2005-2014 Mike Pall. http://luajit.org/
JIT: ON CMOV SSE2 SSE3 SSE4.1 fold cse dce fwd dse narrow loop abc sink fuse
> print(0/0)
nan
> print(math.acos(2))
nan
> 
$ lua
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> print(0/0)
-nan
> print(math.acos(2))
nan
> 
```

Under Windows, Lua 5.1.5 doesn't seem to generate NaNs, only indeterminates, but it distinguishes both with tostring:

```
C:\Lua>lua5.1
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> print(tostring(math.asin(2)))
-1.#IND
> print(tostring(0/0))
-1.#IND
> print(tostring(-(0/0)))
1.#QNAN
>
```

**Comment by davisdude** [comment]
`math.inf` is represented differently depending on Lua versions (luajit, etc.) as well

**Comment by gvx** [comment]
I don't think that is relevant. Ser represents infinity as `1/0` and `-1/0` independently of how Lua represents it. The issue with NaN was that there are two different kinds of NaN in some Lua versions, and Ser only knew how to serialize one of them.

**Comment by davisdude** [comment]
Ah, okay
